// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phys_ent.proto

#ifndef PROTOBUF_phys_5fent_2eproto__INCLUDED
#define PROTOBUF_phys_5fent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ser {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_phys_5fent_2eproto();
void protobuf_InitDefaults_phys_5fent_2eproto();
void protobuf_AssignDesc_phys_5fent_2eproto();
void protobuf_ShutdownFile_phys_5fent_2eproto();

class Box;
class Core;
class SerPhys;
class Sphere;
class Vector3f;

enum SerPhys_Type {
  SerPhys_Type_Sphere = 1,
  SerPhys_Type_Box = 2
};
bool SerPhys_Type_IsValid(int value);
const SerPhys_Type SerPhys_Type_Type_MIN = SerPhys_Type_Sphere;
const SerPhys_Type SerPhys_Type_Type_MAX = SerPhys_Type_Box;
const int SerPhys_Type_Type_ARRAYSIZE = SerPhys_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* SerPhys_Type_descriptor();
inline const ::std::string& SerPhys_Type_Name(SerPhys_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    SerPhys_Type_descriptor(), value);
}
inline bool SerPhys_Type_Parse(
    const ::std::string& name, SerPhys_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SerPhys_Type>(
    SerPhys_Type_descriptor(), name, value);
}
// ===================================================================

class Vector3f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ser.Vector3f) */ {
 public:
  Vector3f();
  virtual ~Vector3f();

  Vector3f(const Vector3f& from);

  inline Vector3f& operator=(const Vector3f& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3f& default_instance();

  static const Vector3f* internal_default_instance();

  void Swap(Vector3f* other);

  // implements Message ----------------------------------------------

  inline Vector3f* New() const { return New(NULL); }

  Vector3f* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Vector3f& from);
  void MergeFrom(const Vector3f& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Vector3f* other);
  void UnsafeMergeFrom(const Vector3f& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // required float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // required float z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:ser.Vector3f)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float x_;
  float y_;
  float z_;
  friend void  protobuf_InitDefaults_phys_5fent_2eproto_impl();
  friend void  protobuf_AddDesc_phys_5fent_2eproto_impl();
  friend void protobuf_AssignDesc_phys_5fent_2eproto();
  friend void protobuf_ShutdownFile_phys_5fent_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Vector3f> Vector3f_default_instance_;

// -------------------------------------------------------------------

class SerPhys : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ser.SerPhys) */ {
 public:
  SerPhys();
  virtual ~SerPhys();

  SerPhys(const SerPhys& from);

  inline SerPhys& operator=(const SerPhys& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SerPhys& default_instance();

  static const SerPhys* internal_default_instance();

  void Swap(SerPhys* other);

  // implements Message ----------------------------------------------

  inline SerPhys* New() const { return New(NULL); }

  SerPhys* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SerPhys& from);
  void MergeFrom(const SerPhys& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SerPhys* other);
  void UnsafeMergeFrom(const SerPhys& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SerPhys_Type Type;
  static const Type Sphere =
    SerPhys_Type_Sphere;
  static const Type Box =
    SerPhys_Type_Box;
  static inline bool Type_IsValid(int value) {
    return SerPhys_Type_IsValid(value);
  }
  static const Type Type_MIN =
    SerPhys_Type_Type_MIN;
  static const Type Type_MAX =
    SerPhys_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    SerPhys_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return SerPhys_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return SerPhys_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return SerPhys_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .ser.SerPhys.Type type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::ser::SerPhys_Type type() const;
  void set_type(::ser::SerPhys_Type value);

  // required .ser.Vector3f pos = 2;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 2;
  const ::ser::Vector3f& pos() const;
  ::ser::Vector3f* mutable_pos();
  ::ser::Vector3f* release_pos();
  void set_allocated_pos(::ser::Vector3f* pos);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(SerPhys)
  // @@protoc_insertion_point(class_scope:ser.SerPhys)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_pos();
  inline void clear_has_pos();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::ser::Vector3f* pos_;
  int type_;
  friend void  protobuf_InitDefaults_phys_5fent_2eproto_impl();
  friend void  protobuf_AddDesc_phys_5fent_2eproto_impl();
  friend void protobuf_AssignDesc_phys_5fent_2eproto();
  friend void protobuf_ShutdownFile_phys_5fent_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SerPhys> SerPhys_default_instance_;

// -------------------------------------------------------------------

class Sphere : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ser.Sphere) */ {
 public:
  Sphere();
  virtual ~Sphere();

  Sphere(const Sphere& from);

  inline Sphere& operator=(const Sphere& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sphere& default_instance();

  static const Sphere* internal_default_instance();

  void Swap(Sphere* other);

  // implements Message ----------------------------------------------

  inline Sphere* New() const { return New(NULL); }

  Sphere* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sphere& from);
  void MergeFrom(const Sphere& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Sphere* other);
  void UnsafeMergeFrom(const Sphere& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  static const int kSerPhysFieldNumber = 100;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ser::SerPhys,
      ::google::protobuf::internal::MessageTypeTraits< ::ser::Sphere >, 11, false >
    serPhys;
  // @@protoc_insertion_point(class_scope:ser.Sphere)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_phys_5fent_2eproto_impl();
  friend void  protobuf_AddDesc_phys_5fent_2eproto_impl();
  friend void protobuf_AssignDesc_phys_5fent_2eproto();
  friend void protobuf_ShutdownFile_phys_5fent_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Sphere> Sphere_default_instance_;

// -------------------------------------------------------------------

class Box : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ser.Box) */ {
 public:
  Box();
  virtual ~Box();

  Box(const Box& from);

  inline Box& operator=(const Box& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Box& default_instance();

  static const Box* internal_default_instance();

  void Swap(Box* other);

  // implements Message ----------------------------------------------

  inline Box* New() const { return New(NULL); }

  Box* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Box& from);
  void MergeFrom(const Box& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Box* other);
  void UnsafeMergeFrom(const Box& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  static const int kSerPhysFieldNumber = 101;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ser::SerPhys,
      ::google::protobuf::internal::MessageTypeTraits< ::ser::Box >, 11, false >
    serPhys;
  // @@protoc_insertion_point(class_scope:ser.Box)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_phys_5fent_2eproto_impl();
  friend void  protobuf_AddDesc_phys_5fent_2eproto_impl();
  friend void protobuf_AssignDesc_phys_5fent_2eproto();
  friend void protobuf_ShutdownFile_phys_5fent_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Box> Box_default_instance_;

// -------------------------------------------------------------------

class Core : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ser.Core) */ {
 public:
  Core();
  virtual ~Core();

  Core(const Core& from);

  inline Core& operator=(const Core& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Core& default_instance();

  static const Core* internal_default_instance();

  void Swap(Core* other);

  // implements Message ----------------------------------------------

  inline Core* New() const { return New(NULL); }

  Core* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Core& from);
  void MergeFrom(const Core& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Core* other);
  void UnsafeMergeFrom(const Core& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ser.SerPhys ojcts = 1;
  int ojcts_size() const;
  void clear_ojcts();
  static const int kOjctsFieldNumber = 1;
  const ::ser::SerPhys& ojcts(int index) const;
  ::ser::SerPhys* mutable_ojcts(int index);
  ::ser::SerPhys* add_ojcts();
  ::google::protobuf::RepeatedPtrField< ::ser::SerPhys >*
      mutable_ojcts();
  const ::google::protobuf::RepeatedPtrField< ::ser::SerPhys >&
      ojcts() const;

  // @@protoc_insertion_point(class_scope:ser.Core)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ser::SerPhys > ojcts_;
  friend void  protobuf_InitDefaults_phys_5fent_2eproto_impl();
  friend void  protobuf_AddDesc_phys_5fent_2eproto_impl();
  friend void protobuf_AssignDesc_phys_5fent_2eproto();
  friend void protobuf_ShutdownFile_phys_5fent_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Core> Core_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Vector3f

// required float x = 1;
inline bool Vector3f::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector3f::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector3f::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector3f::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Vector3f::x() const {
  // @@protoc_insertion_point(field_get:ser.Vector3f.x)
  return x_;
}
inline void Vector3f::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:ser.Vector3f.x)
}

// required float y = 2;
inline bool Vector3f::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector3f::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector3f::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector3f::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Vector3f::y() const {
  // @@protoc_insertion_point(field_get:ser.Vector3f.y)
  return y_;
}
inline void Vector3f::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:ser.Vector3f.y)
}

// required float z = 3;
inline bool Vector3f::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector3f::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector3f::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector3f::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Vector3f::z() const {
  // @@protoc_insertion_point(field_get:ser.Vector3f.z)
  return z_;
}
inline void Vector3f::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:ser.Vector3f.z)
}

inline const Vector3f* Vector3f::internal_default_instance() {
  return &Vector3f_default_instance_.get();
}
// -------------------------------------------------------------------

// SerPhys

// required .ser.SerPhys.Type type = 1;
inline bool SerPhys::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SerPhys::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SerPhys::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SerPhys::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::ser::SerPhys_Type SerPhys::type() const {
  // @@protoc_insertion_point(field_get:ser.SerPhys.type)
  return static_cast< ::ser::SerPhys_Type >(type_);
}
inline void SerPhys::set_type(::ser::SerPhys_Type value) {
  assert(::ser::SerPhys_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:ser.SerPhys.type)
}

// required .ser.Vector3f pos = 2;
inline bool SerPhys::has_pos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SerPhys::set_has_pos() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SerPhys::clear_has_pos() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SerPhys::clear_pos() {
  if (pos_ != NULL) pos_->::ser::Vector3f::Clear();
  clear_has_pos();
}
inline const ::ser::Vector3f& SerPhys::pos() const {
  // @@protoc_insertion_point(field_get:ser.SerPhys.pos)
  return pos_ != NULL ? *pos_
                         : *::ser::Vector3f::internal_default_instance();
}
inline ::ser::Vector3f* SerPhys::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) {
    pos_ = new ::ser::Vector3f;
  }
  // @@protoc_insertion_point(field_mutable:ser.SerPhys.pos)
  return pos_;
}
inline ::ser::Vector3f* SerPhys::release_pos() {
  // @@protoc_insertion_point(field_release:ser.SerPhys.pos)
  clear_has_pos();
  ::ser::Vector3f* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void SerPhys::set_allocated_pos(::ser::Vector3f* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
  // @@protoc_insertion_point(field_set_allocated:ser.SerPhys.pos)
}

inline const SerPhys* SerPhys::internal_default_instance() {
  return &SerPhys_default_instance_.get();
}
// -------------------------------------------------------------------

// Sphere

inline const Sphere* Sphere::internal_default_instance() {
  return &Sphere_default_instance_.get();
}
// -------------------------------------------------------------------

// Box

inline const Box* Box::internal_default_instance() {
  return &Box_default_instance_.get();
}
// -------------------------------------------------------------------

// Core

// repeated .ser.SerPhys ojcts = 1;
inline int Core::ojcts_size() const {
  return ojcts_.size();
}
inline void Core::clear_ojcts() {
  ojcts_.Clear();
}
inline const ::ser::SerPhys& Core::ojcts(int index) const {
  // @@protoc_insertion_point(field_get:ser.Core.ojcts)
  return ojcts_.Get(index);
}
inline ::ser::SerPhys* Core::mutable_ojcts(int index) {
  // @@protoc_insertion_point(field_mutable:ser.Core.ojcts)
  return ojcts_.Mutable(index);
}
inline ::ser::SerPhys* Core::add_ojcts() {
  // @@protoc_insertion_point(field_add:ser.Core.ojcts)
  return ojcts_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ser::SerPhys >*
Core::mutable_ojcts() {
  // @@protoc_insertion_point(field_mutable_list:ser.Core.ojcts)
  return &ojcts_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ser::SerPhys >&
Core::ojcts() const {
  // @@protoc_insertion_point(field_list:ser.Core.ojcts)
  return ojcts_;
}

inline const Core* Core::internal_default_instance() {
  return &Core_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ser

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ser::SerPhys_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ser::SerPhys_Type>() {
  return ::ser::SerPhys_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_phys_5fent_2eproto__INCLUDED
